Repository PaddlePaddle/PaConvert, pull requests merged in 2023-07, with the labels that each got.

#145 转换规则 No.245/249/250
  paconvert/api_mapping.json
  tests/test_Tensor_take_along_dim.py
  tests/test_linalg_matrix_power.py
  tests/test_take_along_dim.py
Labels: contributor, HappyOpenSource, status: proposed

#144 转换规则 No.216/217
  paconvert/api_mapping.json
  tests/test_linalg_inv.py
  tests/test_linalg_qr.py
Labels: contributor, HappyOpenSource, status: proposed

#149 转换规则 No.272/282/318/324/326
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_Tensor_histogram.py
  tests/test_corrcoef.py
  tests/test_nn_functional_mish.py
  tests/test_special_log_softmax.py
Labels: contributor, HappyOpenSource, status: proposed

#142 转换规则 No.16/17/18
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_cummin.py
  tests/test_searchsorted.py
  tests/test_vander.py
Labels: contributor, HappyOpenSource, status: proposed

#133 转换规则 No.234/236/237
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_utils_data_ChainDataset.py
  tests/test_utils_data_Subset.py
  tests/test_utils_data_TensorDataset.py
Labels: contributor, HappyOpenSource, status: not progressed

#148 转换规则 No.252/256/267
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_dsplit.py
  tests/test_linalg_multi_dot.py
  tests/test_special_expm1.py
Labels: contributor, HappyOpenSource, status: proposed

#163 转换规则 No.19 torch.geqrf
  tests/test_geqrf.py
Labels: contributor, HappyOpenSource, status: proposed

#169 转换规则 No.198 torch.distribution.kl.register_kl
  paconvert/api_mapping.json
  tests/test_distributions_kl_register_kl.py
Labels: contributor, status: proposed

#167 转换规则 No. 5/6/7/8
  paconvert/api_mapping.json
  tests/test_i0.py
  tests/test_nextafter.py
  tests/test_polygamma.py
  tests/test_quantile.py
Labels: contributor, status: proposed

#174 转换规则 No.299/305/316/317/322
  paconvert/api_mapping.json
  tests/test_Tensor_corrcoef.py
  tests/test_cumulative_trapezoid.py
  tests/test_special_i0.py
  tests/test_special_i1.py
  tests/test_special_i1e.py
Labels: contributor, HappyOpenSource, status: proposed

#122 转换规则 No. 114-120
  paconvert/api_mapping.json
  tests/test_autograd_backward.py
  tests/test_autograd_functional_hessian.py
  tests/test_autograd_functional_jacobian.py
  tests/test_autograd_functional_jvp.py
  tests/test_autograd_functional_vjp.py
Labels: contributor, HappyOpenSource, status: not progressed

#179 转换规则 No. 92/93
  paconvert/api_mapping.json
  tests/test_Tensor_nan_to_num.py
  tests/test_Tensor_nextafter.py
Labels: contributor, HappyOpenSource, status: proposed

#180 转换规则 No. 141/142
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_cuda_nvtx_range_pop.py
  tests/test_cuda_nvtx_range_push.py
Labels: contributor, HappyOpenSource, status: proposed

#172 转换规则 No. 366
  paconvert/api_mapping.json
  tests/test_from_dlpack.py
Labels: contributor, HappyOpenSource, status: proposed

#182 转换规则 No. 193/194/195
  paconvert/api_mapping.json
  tests/test_distributions_transforms_SoftmaxTransform.py
  tests/test_distributions_transforms_StackTransform.py
  tests/test_distributions_transforms_StickBreakingTransform.py
Labels: contributor, HappyOpenSource, status: proposed

#187 转换规则 No. 402-408
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_DoubleTensor.py
  tests/test_HalfTensor.py
  tests/test_ShortTensor.py
  tests/test_cuda_DoubleTensor.py
  tests/test_cuda_HalfTensor.py
  tests/test_cuda_ShortTensor.py
Labels: contributor, HappyOpenSource, status: proposed

#191 转换规则 No. 352/353
  tests/test_cuda_mem_get_info.py
  tests/test_cuda_memory_usage.py
Labels: contributor, HappyOpenSource

#189 转换规则 No. 378
  paconvert/api_mapping.json
  tests/test_linalg_vander.py
Labels: contributor, HappyOpenSource

#185 转换规则 No. 271/273/280/283/297/298/301/325/337/343-344
  tests/test_Tensor_bitwise_right_shift.py
  tests/test_Tensor_dsplit.py
  tests/test_Tensor_hsplit.py
  tests/test_Tensor_is_conj.py
  tests/test_Tensor_vsplit.py
  tests/test_bitwise_right_shift.py
  tests/test_get_deterministic_debug_mode.py
  tests/test_hsplit.py
  tests/test_is_conj.py
  tests/test_set_deterministic_debug_mode.py
  tests/test_vsplit.py
Labels: contributor, HappyOpenSource, status: proposed

#190 转换规则 No. 165-180
  paconvert/api_mapping.json
  tests/test_distributions_bernoulli_Bernoulli.py
  tests/test_distributions_binomial_Binomial.py
  tests/test_distributions_categorical_Categorical.py
  tests/test_distributions_cauchy_Cauchy.py
  tests/test_distributions_continuous_bernoulli_ContinuousBernoulli.py
  tests/test_distributions_dirichlet_Dirichlet.py
  tests/test_distributions_exp_family_ExponentialFamily.py
  tests/test_distributions_exponential_Exponential.py
  tests/test_distributions_geometric_Geometric.py
  tests/test_distributions_gumbel_Gumbel.py
  tests/test_distributions_independent_Independent.py
  tests/test_distributions_laplace_Laplace.py
  tests/test_distributions_log_normal_LogNormal.py
  tests/test_distributions_multinomial_Multinomial.py
  tests/test_distributions_normal_Normal.py
  tests/test_distributions_one_hot_categorical_OneHotCategorical.py
Labels: contributor, HappyOpenSource

#193 转换规则 No. 94/95/96
  paconvert/api_mapping.json
  tests/test_Tensor_nanquantile.py
  tests/test_Tensor_polygamma.py
  tests/test_Tensor_qr.py
Labels: contributor, HappyOpenSource

#183 转换规则 No. 258/263/285
  paconvert/api_mapping.json
  tests/test_nn_HuberLoss.py
  tests/test_nn_functional_huber_loss.py
  tests/test_special_erfinv.py
Labels: contributor, HappyOpenSource, status: proposed

#195 转换规则 No. 181-184
  paconvert/api_alias_mapping.json
  paconvert/api_mapping.json
  tests/test_distributions_Bernoulli.py
  tests/test_distributions_Beta.py
  tests/test_distributions_Binomial.py
  tests/test_distributions_Categorical.py
  tests/test_distributions_Cauchy.py
  tests/test_distributions_ComposeTransform.py
  tests/test_distributions_ContinuousBernoulli.py
  tests/test_distributions_Dirichlet.py
  tests/test_distributions_Exponential.py
  tests/test_distributions_ExponentialFamily.py
  tests/test_distributions_Geometric.py
  tests/test_distributions_Gumbel.py
  tests/test_distributions_Independent.py
  tests/test_distributions_Laplace.py
  tests/test_distributions_LogNormal.py
  tests/test_distributions_Multinomial.py
  tests/test_distributions_Normal.py
  tests/test_distributions_OneHotCategorical.py
  tests/test_distributions_SigmoidTransform.py
  tests/test_distributions_SoftmaxTransform.py
  tests/test_distributions_StackTransform.py
  tests/test_distributions_StickBreakingTransform.py
  tests/test_distributions_Transform.py
  tests/test_distributions_TransformedDistribution.py
  tests/test_distributions_Uniform.py
Labels: contributor, HappyOpenSource

#198 转换规则 No. 323/333
  paconvert/api_mapping.json
  tests/test_nn_GLU.py
  tests/test_special_polygamma.py
Labels: contributor, HappyOpenSource, status: proposed

#200 转换规则 No. 127
  tests/test_cuda_set_rng_state.py
Labels: contributor, HappyOpenSource, status: proposed

#201 转换规则 No.274
  tests/test_Tensor_is_coalesced.py
Labels: contributor, status: proposed

#203 转换规则 No.47/244
  paconvert/api_mapping.json
  tests/test_testing_assert_close.py
Labels: contributor, status: proposed

#204 转换规则 No.227
  paconvert/api_mapping.json
  tests/test_random_initial_seed.py
Labels: contributor, status: proposed

#207 转换规则 No. 159-163
  tests/test_distributed_all_gather_multigpu.py
  tests/test_distributed_all_reduce_multigpu.py
  tests/test_distributed_broadcast_multigpu.py
  tests/test_distributed_reduce_multigpu.py
  tests/test_distributed_reduce_scatter_multigpu.py
Labels: contributor, status: proposed

#213 转换规则 No.338
  paconvert/api_mapping.json
  tests/test_asarray.py
Labels: contributor, HappyOpenSource, status: proposed

#214 转换规则 No.339-342/345-348
  tests/test_Tensor_diagonal_scatter.py
  tests/test_Tensor_scatter_reduce.py
  tests/test_Tensor_select_scatter.py
  tests/test_Tensor_slice_scatter.py
  tests/test_diagonal_scatter.py
  tests/test_scatter_reduce.py
  tests/test_select_scatter.py
  tests/test_slice_scatter.py
Labels: contributor, HappyOpenSource, status: proposed
