Repository PaddlePaddle/PaConvert, pull requests merged in 2023-08, with the labels that each got.

#134 转换规则 No.48 RNNBase
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_nn_layer_rnn_RNNBase.py
Labels: contributor, HappyOpenSource, status: proposed

#197 转换规则 No. 196/197/232/233/319
  tests/test_distributions_constraint_registry_ConstraintRegistry.py
  tests/test_distributions_constraints_Constraint.py
  tests/test_histogram.py
  tests/test_utils_cpp_extension_include_paths.py
  tests/test_utils_cpp_extension_load_inline.py
Labels: contributor, HappyOpenSource, status: proposed

#202 转换规则 No.86
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  paconvert/transformer/basic_transformer.py
  tests/test_Tensor_is_signed.py
Labels: contributor, HappyOpenSource, status: proposed

#211 转换规则 No.80 torch.Tensor.geqrf
  tests/test_Tensor_geqrf.py
Labels: contributor, HappyOpenSource, status: proposed

#212 转换规则 No.334
  paconvert/api_mapping.json
  tests/test_special_round.py
Labels: contributor, HappyOpenSource, status: proposed

#199 转换规则 No. 349/350
  paconvert/api_matcher.py
  paconvert/attribute_mapping.json
  paconvert/transformer/basic_transformer.py
  tests/test_Tensor_H.py
  tests/test_Tensor_mH.py
  tests/test_Tensor_mT.py
Labels: contributor, HappyOpenSource, status: proposed

#209 转换规则 No. 221-226
  paconvert/api_mapping.json
  tests/test_distributed_rpc_WorkerInfo.py
  tests/test_distributed_rpc_functions_async_execution.py
  tests/test_distributed_rpc_get_worker_info.py
  tests/test_distributed_rpc_rpc_async.py
  tests/test_distributed_rpc_rpc_sync.py
  tests/test_distributed_rpc_shutdown.py
Labels: contributor, HappyOpenSource, status: proposed

#186 转换规则 No. 380/381/391-401
  tests/test_nn_Module_bfloat16.py
  tests/test_nn_Module_double.py
  tests/test_nn_Module_float.py
  tests/test_nn_Module_half.py
  tests/test_nn_Module_register_full_backward_hook.py
  tests/test_nn_Module_register_full_backward_pre_hook.py
  tests/test_nn_Module_requires_grad_.py
  tests/test_nn_Module_to.py
  tests/test_nn_Module_to_empty.py
  tests/test_nn_Module_type.py
  tests/test_nn_Module_zero_grad.py
  tests/test_onnx_disable_log.py
  tests/test_onnx_enable_log.py
Labels: contributor, HappyOpenSource, status: proposed

#225 转换规则 No. 360
  tests/test_linalg_matrix_exp.py
Labels: contributor, HappyOpenSource, status: proposed

#217 转换规则 No.243-300 其他未领取项
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_Tensor_sparse_resize_.py
  tests/test_Tensor_sparse_resize_and_clear_.py
  tests/test_autograd_Function.py
  tests/test_autograd_Function_backward.py
  tests/test_autograd_Function_forward.py
  tests/test_autograd_function_FunctionCtx_mark_dirty.py
  tests/test_autograd_function_FunctionCtx_mark_non_differentiable.py
  tests/test_autograd_function_FunctionCtx_save_for_backward.py
  tests/test_autograd_function_FunctionCtx_set_materialize_grads.py
  tests/test_autograd_graph_saved_tensors_hooks.py
  tests/test_autograd_profiler_profile_self_cpu_time_total.py
  tests/test_cuda_StreamContext.py
  tests/test_cuda_set_stream.py
  tests/test_gradient.py
  tests/test_linalg_cholesky_ex.py
  tests/test_linalg_inv_ex.py
  tests/test_linalg_matrix_norm.py
  tests/test_linalg_svdvals.py
  tests/test_linalg_vector_norm.py
  tests/test_nn_LazyBatchNorm1d.py
  tests/test_nn_LazyBatchNorm2d.py
  tests/test_nn_LazyBatchNorm3d.py
  tests/test_nn_Mish.py
  tests/test_nn_functional_group_norm.py
  tests/test_nn_utils_parametrizations_spectral_norm.py
  tests/test_nn_utils_parametrize_is_parametrized.py
  tests/test_positive.py
  tests/test_profiler_ProfilerAction.py
  tests/test_profiler_ProfilerActivity.py
  tests/test_special_entr.py
  tests/test_special_erfc.py
  tests/test_special_exp2.py
  tests/test_special_expit.py
  tests/test_special_gammaln.py
Labels: contributor, HappyOpenSource, status: proposed

#224 转换规则 No. 309
  paconvert/api_mapping.json
  tests/test_trapezoid.py
Labels: contributor, HappyOpenSource, status: proposed

#160 转换规则 No.26 `torch.svd`
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_svd.py
Labels: contributor, HappyOpenSource, status: proposed

#234 转换规则 No. 303/330/336
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_optim_lr_scheduler_LinearLR.py
  tests/test_special_erfcx.py
  tests/test_special_xlogy.py
Labels: contributor, HappyOpenSource, status: proposed

#219 转换规则 No.87
  tests/test_Tensor_lstsq.py
Labels: contributor, HappyOpenSource, status: not progressed

#235 转换规则 No. 310-315/320/321/335
  tests/test_Tensor_bitwise_left_shift.py
  tests/test_Tensor_resolve_conj.py
  tests/test_Tensor_resolve_neg.py
  tests/test_bitwise_left_shift.py
  tests/test_isin.py
  tests/test_nn_LazyInstanceNorm1d.py
  tests/test_nn_LazyInstanceNorm2d.py
  tests/test_nn_LazyInstanceNorm3d.py
  tests/test_resolve_neg.py
Labels: contributor, HappyOpenSource, status: proposed

#237 转换规则 No. 331
  paconvert/api_mapping.json
  tests/test_Tensor_conj_physical.py
Labels: contributor, HappyOpenSource, status: proposed

#244 转换规则 No.373/375/376
  paconvert/api_alias_mapping.json
  tests/test_cuda_is_current_stream_capturing.py
  tests/test_distributions_CumulativeDistributionTransform.py
  tests/test_distributions_SoftplusTransform.py
Labels: contributor, HappyOpenSource

#243 转换规则 No. 370
  paconvert/api_mapping.json
  tests/test_nn_functional_dropout1d.py
Labels: contributor, HappyOpenSource

#250 转换规则 No.164
  paconvert/api_alias_mapping.json
  tests/test_distributions_Distribution.py
Labels: contributor, HappyOpenSource

#245 转换规则 No.384-387
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_nn_Module_get_buffer.py
  tests/test_nn_Module_get_parameter.py
  tests/test_nn_Module_get_submodule.py
  tests/test_nn_Module_register_parameter.py
Labels: contributor, HappyOpenSource

#239 转换规则 No. 362
  paconvert/api_mapping.json
  tests/test_special_softmax.py
Labels: contributor, HappyOpenSource, status: proposed

#120 转换规则No64 torch.nn.functional.max_pool1d
  paconvert/api_mapping.json
  tests/test_nn_functional_max_pool1d.py
Labels: contributor, HappyOpenSource, status: proposed

#236 转换规则 No. 302
  paconvert/api_mapping.json
  tests/test_sparse_csr_tensor.py
Labels: contributor, HappyOpenSource, status: proposed

#241 转换规则 No. 304/306/308/327-329/332/351/363/365/369/371
  tests/test_Tensor_bitwise_left_shift_.py
  tests/test_Tensor_bitwise_right_shift_.py
  tests/test_Tensor_retains_grad.py
  tests/test_autograd_Function_jvp.py
  tests/test_distributed_monitored_barrier.py
  tests/test_layout.py
  tests/test_nn_utils_stateless_functional_call.py
  tests/test_resolve_conj.py
  tests/test_sparse_sampled_addmm.py
  tests/test_special_multigammaln.py
  tests/test_testing_make_tensor.py
  tests/test_utils_data_default_convert.py
Labels: contributor, HappyOpenSource, status: proposed

#246 转换规则 No.307/372
  paconvert/api_mapping.json
  tests/test_autocast.py
  tests/test_cpu_amp_autocast.py
Labels: contributor, HappyOpenSource

#254 转换规则 No.368/374/377
  paconvert/api_alias_mapping.json
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_distributions_CatTransform.py
  tests/test_linalg_lu.py
  tests/test_nn_Dropout1d.py
Labels: contributor, HappyOpenSource

#258 转换规则 No.235/239
  paconvert/api_mapping.json
  tests/test_utils_data_ConcatDataset.py
  tests/test_utils_data_get_worker_info.py
Labels: contributor, HappyOpenSource

#248 转换规则 No.228/229
  paconvert/api_mapping.json
  tests/test_sparse_addmm.py
  tests/test_sparse_mm.py
Labels: contributor, HappyOpenSource

#257 转换规则 No.359
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_linalg_solve_triangular.py
Labels: contributor, HappyOpenSource

#259 Update test_Tensor_index_copy_.py
  tests/test_Tensor_index_copy_.py
Labels: contributor, HappyOpenSource
