Repository PaddlePaddle/PaConvert, pull requests merged in 2023-09, with the labels that each got.

#263 转换规则 No.43/97/98/100
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_Tensor_resize_as_.py
  tests/test_Tensor_round_.py
  tests/test_Tensor_scatter_add.py
  tests/test_nn_Threshold.py
Labels: contributor, HappyOpenSource

#256 转换规则 No.358/361
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_linalg_lu_factor.py
  tests/test_linalg_lu_factor_ex.py
Labels: contributor, HappyOpenSource

#118 转换规则No66-70 torch.nn.functional.pairwise_distance
  paconvert/api_mapping.json
  tests/test_nn_functional_cosine_embedding_loss.py
  tests/test_nn_functional_gumbel_softmax.py
  tests/test_nn_functional_hinge_embedding_loss.py
  tests/test_nn_functional_pairwise_distance.py
  tests/test_nn_functional_poisson_nll_loss.py
Labels: contributor, HappyOpenSource, status: proposed

#265 转换规则 No.155-158
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/distributed/all_to_all.py
  tests/distributed/common.py
  tests/distributed/convert.sh
  tests/distributed/reduce_scatter.py
  tests/distributed/run.sh
  tests/distributed/scatter.py
  tests/distributed/scatter_object_list.py
Labels: contributor, HappyOpenSource

#270 Fix tests/distributed/convert.sh
  tests/distributed/run.sh
  tests/distributed/run_test.sh
Labels: contributor, HappyOpenSource

#274 Fix README.md
  README.md
Labels: contributor

#273 转换规则 No. 219/230
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_profiler_schedule.py
  tests/test_sparse_softmax.py
Labels: contributor, HappyOpenSource

#181 转换规则 No. 153
  paconvert/api_mapping.json
  tests/test_distributed_all_gather_object.py
Labels: contributor, HappyOpenSource, status: proposed

#278 转换规则 No.77-78
  tests/test_Tensor_copysign.py
  tests/test_Tensor_dequantize.py
Labels: contributor, HappyOpenSource

#286 转换规则 添加部分 inplace api 的映射 PART.03
  paconvert/api_mapping.json
  tests/test_Tensor_addmm_.py
  tests/test_Tensor_i0_.py
  tests/test_Tensor_sigmoid_.py
  tests/test_Tensor_trunc_.py
Labels: contributor

#287 转换规则 添加 inplace subtract_ api 的映射 PART.sub
  paconvert/api_mapping.json
  tests/test_Tensor_sub_.py
Labels: contributor

#288 转换规则 添加 inplace detach_ api 的映射 PART.detach
  tests/test_Tensor_detach_.py
Labels: contributor

#285 转换规则 添加 inplace `divide_` api 的映射 PART.divide
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_Tensor_div_.py
  tests/test_Tensor_divide_.py
  tests/test_Tensor_true_divide_.py
Labels: contributor

#296 fix `Tensor.detach_` unittests error
  tests/test_Tensor_detach_.py
Labels: contributor

#284 转换规则 添加部分 inplace api 的映射 PART.02
  paconvert/api_mapping.json
  tests/test_Tensor_lcm_.py
  tests/test_Tensor_ldexp_.py
  tests/test_Tensor_lgamma_.py
  tests/test_Tensor_log10_.py
  tests/test_Tensor_log1p_.py
  tests/test_Tensor_log2_.py
  tests/test_Tensor_log_.py
  tests/test_Tensor_logit_.py
  tests/test_Tensor_nan_to_num_.py
  tests/test_Tensor_neg_.py
  tests/test_Tensor_negative_.py
  tests/test_Tensor_polygamma_.py
  tests/test_Tensor_pow_.py
Labels: contributor

#294 转换规则 添加部分 inplace compare api 的映射 PART.cmp
  paconvert/api_alias_mapping.json
  paconvert/api_mapping.json
  paconvert/api_matcher.py
  tests/test_Tensor_eq_.py
  tests/test_Tensor_ge_.py
  tests/test_Tensor_greater_.py
  tests/test_Tensor_greater_equal_.py
  tests/test_Tensor_gt_.py
  tests/test_Tensor_le_.py
  tests/test_Tensor_less_.py
  tests/test_Tensor_less_equal_.py
  tests/test_Tensor_logical_and_.py
  tests/test_Tensor_logical_not_.py
  tests/test_Tensor_logical_or_.py
  tests/test_Tensor_logical_xor_.py
  tests/test_Tensor_lt_.py
  tests/test_Tensor_ne_.py
  tests/test_Tensor_not_equal_.py
Labels: contributor

#302 转换规则 添加部分 inplace api 的映射 PART.04
  paconvert/api_mapping.json
  tests/test_Tensor_abs_.py
  tests/test_Tensor_acos_.py
  tests/test_Tensor_arccos_.py
  tests/test_Tensor_arccosh_.py
  tests/test_Tensor_arcsin_.py
  tests/test_Tensor_arcsinh_.py
  tests/test_Tensor_arctan_.py
  tests/test_Tensor_arctanh_.py
  tests/test_Tensor_cos_.py
  tests/test_Tensor_cosh_.py
  tests/test_Tensor_erf_.py
  tests/test_Tensor_expm1_.py
  tests/test_Tensor_renorm_.py
  tests/test_Tensor_sin_.py
  tests/test_Tensor_sinh_.py
  tests/test_Tensor_square_.py
  tests/test_Tensor_tan_.py
  tests/test_Tensor_tril_.py
  tests/test_Tensor_triu_.py
Labels: contributor
